---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate
  namespace: new-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-todo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pod-todo
    spec:
      containers:
        - name: todo-list
          image: luffsenpai/todo:REPLACE_TAG
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: new-namespace
spec:
  type: NodePort
  selector:
    app: my-pod
  ports:
    - port: 80
      targetPort: 8080
